#!/bin/bash
# vi: set sw=4 tw=76 :

. /etc/fscleaner.conf

case ${1} in
    daily)
        for item in ${daily_duperemove} ; do
            cd ${item}
            duperemove -x -d ${duperemove_opts} ${item} || true
        done

        for item in ${daily_sparse} ; do
            cd ${item}
            find ${item} -xdev -size +${sparse_size} -exec fallocate -d '{}' \; || true
        done

        for item in ${daily_e4defrag} ; do
            cd ${item}
            e4defrag ${item} || true
        done

        for item in ${daily_btrfs_defrag} ; do
            cd ${item}
            btrfs filesystem defrag ${btrfs_defrag_opts} ${item} || true
        done

        for item in ${daily_btrfs_scrub} ; do
            cd ${item}
            btrfs scrub start ${btrfs_scrub_opts} ${item} || true
        done

        for item in ${daily_btrfs_balance} ; do
            cd ${item}
            btrfs balance start ${btrfs_balance_opts} ${item} || true
        done

        if [ ${daily_fstrim} ] ; then
            cd ${item}
            fstrim -a ${fstrim_opts} || true
        fi
        ;;
    weekly)
        for item in ${weekly_duperemove} ; do
            cd ${item}
            duperemove -x -d ${duperemove_opts} ${item} || true
        done

        for item in ${weekly_sparse} ; do
            cd ${item}
            find ${item} -xdev -size +${sparse_size} -exec fallocate -d '{}' \; || true
        done

        for item in ${weekly_e4defrag} ; do
            cd ${item}
            e4defrag ${item} || true
        done

        for item in ${weekly_btrfs_defrag} ; do
            cd ${item}
            btrfs filesystem defrag ${btrfs_defrag_opts} ${item} || true
        done

        for item in ${weekly_btrfs_scrub} ; do
            cd ${item}
            btrfs scrub start ${btrfs_scrub_opts} ${item} || true
        done

        for item in ${weekly_btrfs_balance} ; do
            cd ${item}
            btrfs balance start ${btrfs_balance_opts} ${item} || true
        done

        if [ ${weekly_fstrim} ] ; then
            cd ${item}
            fstrim -a ${fstrim_opts} || true
        fi
        ;;
    daily)
        for item in ${daily_duperemove} ; do
            cd ${item}
            duperemove -x -d ${duperemove_opts} ${item} || true
        done

        for item in ${daily_sparse} ; do
            cd ${item}
            find ${item} -xdev -size +${sparse_size} -exec fallocate -d '{}' \; || true
        done

        for item in ${daily_e4defrag} ; do
            cd ${item}
            e4defrag ${item} || true
        done

        for item in ${daily_btrfs_defrag} ; do
            cd ${item}
            btrfs filesystem defrag ${btrfs_defrag_opts} ${item} || true
        done

        for item in ${daily_btrfs_scrub} ; do
            cd ${item}
            btrfs scrub start ${btrfs_scrub_opts} ${item} || true
        done

        for item in ${daily_btrfs_balance} ; do
            cd ${item}
            btrfs balance start ${btrfs_balance_opts} ${item} || true
        done

        if [ ${daily_fstrim} ] ; then
            cd ${item}
            fstrim -a ${fstrim_opts} || true
        fi
        ;;
esac
