#!/bin/bash
# vi: set sw=4 tw=76 :

. /etc/fscleaner.conf

for item in ${${1}_e4defrag} ; do
    e4defrag ${item} || true
done
if [ ${${1}_fstrim} ] ; then
    fstrim -a ${fstrim_opts} || true
fi
for item in ${${1}_zerofree} ; do
    zerofree ${item} || true
done
for op in balance scrub defrag ; do
    for item in ${${1}_btrfs_${op}} ; do
        btrfs ${op} start ${btrfs_${op}_opts} ${item} || true
    done
done
