#!/bin/bash

. /etc/conf.d/snapback

do_snap() {
    if [ -z ${RUN} ] ; then
        exit 0;
    fi
    if [ -z ${CLEANFREQ} ] ; then
        CLEANFREQ="1 * * *"
    fi
    snaphour=`echo ${CLEANFREQ} | cut -d ' ' -f 1 -s`
    if [ ${snaphour} != "*" ] ; then
        if [ `date "+%_H"` != ${snaphour} ] ; then
            exit 0;
        fi
    fi
    snapmday=`echo ${CLEANFREQ} | cut -d ' ' -f 2 -s`
    if [ ${snapmday} != "*" ] ; then
        if [ `date "+%_d"` != ${snapmday} ] ; then
            exit 0;
        fi
    fi
    snapmonth=`echo ${CLEANFREQ} | cut -d ' ' -f 3 -s`
    if [ ${snapmonth} != "*" ] ; then
        if [ `date "+%_m"` != ${snapmonth} ] ; then
            exit 0;
        fi
    fi
    snapwday=`echo ${CLEANFREQ} | cut -d ' ' -f 4 -s`
    if [ ${snapwday} != "*" ] ; then
        if [ `date "+%w"` != ${snapwday} ] ; then
            if [ `date "+%u"` != $((${snapwday}-7)) ] ; then
                exit 0;
            fi
        fi
    fi
}

for lvol in ${TARGETS} ; do
    snaps=`lvs --noheadings --options lv_path | grep "${lvol}.[[:digit:]]{8}" | cut -d / -f 3,4 -s | sort`
    if [ `echo ${snaps} | wc -l` -le ${KEEPSNAPS} ] ; then
        continue ;
    fi
    for count in seq ${KEEPSNAPS} ; do
        snaps=`echo ${snaps} | tail -c +1`
    done
    for oldsnap in ${snaps} ; do
        lvremove ${oldsnap}
    done
done
