#!/bin/bash

print_help() {
    echo "Usage: disowned [dirname]"
}

if [ -z ${1} ] ; then
    print_help;
    exit 0;
fi

case ${1} in
    "-h") print_help ; exit 0 ;;
    "-?") print_help ; exit 0 ;;
    "--help") print_help ; exit 0 ;;
esac

filelist=$(find ${1})
for file in ${filelist} ; do
    file=$(realpath -s ${file})
    equery b -e ${file} > /dev/null
    if [ $? = 1 ] ; then
        echo ${file}
    fi
done
