#!/bin/bash

. /etc/conf.d/snapback

do_snap() {
    if [ -z ${RUN} ] ; then
        return false;
    fi
    if [ -z ${SNAPFREQ} ] ; then
        SNAPFREQ="0 * * *"
    fi
    snaphour=`echo ${SNAPFREQ} | cut -d ' ' -f 1 -s`
    if [ ${snaphour} != "*" ] ; then
        if [ `date "+%_H"` != ${snaphour} ] ; then
            return false;
        fi
    fi
    snapmday=`echo ${SNAPFREQ} | cut -d ' ' -f 2 -s`
    if [ ${snapmday} != "*" ] ; then
        if [ `date "+%_d"` != ${snapmday} ] ; then
            return false;
        fi
    fi
    snapmonth=`echo ${SNAPFREQ} | cut -d ' ' -f 3 -s`
    if [ ${snapmonth} != "*" ] ; then
        if [ `date "+%_m"` != ${snapmonth} ] ; then
            return false;
        fi
    fi
    snapwday=`echo ${SNAPFREQ} | cut -d ' ' -f 4 -s`
    if [ ${snapwday} != "*" ] ; then
        if [ `date "+%w"` != ${snapwday} ] ; then
            if [ `date "+%u"` != $((${snapwday}-7)) ] ; then
                return false;
            fi
        fi
    fi
    return true;
}

if do_snap ; then
    for lvol in ${TARGETS} ; do
        snaps=`lvs --noheadings --options lv_path | grep "${lvol}.[[:digit:]]{8}" | cut -d / -f 3,4 -s | sort`
        if [ `echo ${snaps} | wc -l` -le ${KEEPSNAPS} ] ; then
            continue ;
        fi
        for count in seq ${KEEPSNAPS} ; do
            snaps=`echo ${snaps} | tail -c +1`
        done
        for oldsnap in ${snaps} ; do
            lvremove ${oldsnap}
        done
    done
fi
